/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8rfENuYIFf1
 */
import { Button } from "@/components/atoms/button";
import { Input } from "@/components/atoms/ui/input";

import { Form, FormControl, FormField, FormItem, FormMessage } from "@/components/atoms/ui/form";

import { useWaitList } from "../hooks/useWaitList";

export function WaitList() {
  const { onSubmit, isSubmitting, form, errors } = useWaitList();

  return (
    <div className="w-full">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)}>
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormControl>
                  <Input
                    placeholder="Enter your email address..."
                    type="email"
                    isError={!!errors.email}
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button
            className="mt-5 w-full"
            type="submit"
            isLoading={isSubmitting}
            variant={"default"}
          >
            Kirim
          </Button>
        </form>
      </Form>
    </div>
  );
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  );
}
