/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8rfENuYIFf1
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PDF_PROJECT_PROFILE } from "@/constants";
import Link from "next/link";

export function Hero() {
  return (
    <main className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
              Innovation Queue
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              If you're interested in our vision and mission, drop your email to
              be the first to know about exciting updates!
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <form className="flex space-x-2">
              <Input
                className="max-w-lg flex-1"
                placeholder="Enter your email"
                type="email"
              />
              <Button className="bg-[#2F4F4F] text-white" type="submit">
                Submit
              </Button>
            </form>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              You can read the details here :
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <Button variant="outline">
              <Link
                className="flex items-center space-x-2"
                download
                target="_blank"
                href={PDF_PROJECT_PROFILE}
              >
                <DownloadIcon className="w-4 h-4" />
                <span>Download PDF</span>
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </main>
  );
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  );
}
